// netlify/functions/email-summary.js
// Build a friendly summary of a concierge thread and send via Resend API to OWNER_NOTIFY_EMAIL.
// POST JSON: { concierge_id: uuid, send_to?: email }  (if send_to not provided, uses OWNER_NOTIFY_EMAIL env var)

const { supabase, respond } = require('./utils');

const RESEND_URL = 'https://api.resend.com/emails';

function formatConversation(messages) {
  // returns HTML list
  return messages
    .map((m) => {
      const time = m.created_at ? new Date(m.created_at).toLocaleString() : '';
      const who = m.sender || 'client';
      // escape basic HTML (minimal)
      const body = (m.body || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br/>');
      return `<p><strong>[${time}] ${who}:</strong><br/>${body}</p>`;
    })
    .join('\n');
}

async function generateAISummary(messages, client) {
  const OPENAI_URL = 'https://api.openai.com/v1/chat/completions';
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return '';

  const lastMessages = (messages || []).slice(-10).map(m => `${m.sender}: ${m.body}`).join('\n');
  const prompt = `Summarize the following travel concierge conversation into a short professional paragraph (2-4 sentences). Mention the client's name and contact details where present and list key requests and next recommended steps. Conversation:\n${lastMessages}\nClient details: ${client?.name || ''} ${client?.email || ''} ${client?.phone || ''}`;

  try {
    const res = await fetch(OPENAI_URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: process.env.OPENAI_MODEL || 'gpt-3.5-turbo',
        messages: [{ role: 'system', content: 'You summarize concierge/travel conversation.' }, { role: 'user', content: prompt }],
        temperature: 0.2,
        max_tokens: 200
      })
    });
    if (!res.ok) {
      const txt = await res.text().catch(() => '');
      console.warn('openai summary failed', res.status, txt);
      return '';
    }
    const data = await res.json();
    return data?.choices?.[0]?.message?.content?.trim() ?? '';
  } catch (e) {
    console.error('generateAISummary error', e);
    return '';
  }
}

module.exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return respond(204, {});
  if (event.httpMethod !== 'POST') return respond(405, { error: 'Method Not Allowed' });

  if (!supabase) return respond(500, { error: 'Supabase client not configured' });

  let body = {};
  try { body = event.body ? JSON.parse(event.body) : {}; } catch (e) { return respond(400, { error: 'Invalid JSON' }); }

  const concierge_id = body.concierge_id;
  const send_to = body.send_to || process.env.OWNER_NOTIFY_EMAIL;
  const from = process.env.SENDER_EMAIL || `no-reply@${(process.env.SUPABASE_URL || 'fhjdreamdestinations.com').replace(/^https?:\/\//,'')}`;

  if (!concierge_id) return respond(400, { error: 'concierge_id required' });
  if (!send_to) return respond(400, { error: 'OWNER_NOTIFY_EMAIL not configured and send_to not provided' });

  try {
    // fetch parent and messages
    const { data: parent, error: pErr } = await supabase.from('concierge').select('id, name, email, phone, message, status, created_at').eq('id', concierge_id).single();
    if (pErr) throw pErr;

    const { data: messages, error: mErr } = await supabase.from('concierge_messages').select('sender, body, metadata, created_at').eq('concierge_id', concierge_id).order('created_at', { ascending: true });
    if (mErr) throw mErr;

    const convHtml = formatConversation(messages || []);
    const aiSummary = await generateAISummary(messages || [], parent || {});
    const subject = `New Concierge Inquiry: ${parent?.name || parent?.email || 'No name'} — ${parent?.message ? parent.message.slice(0, 40) : ''}`;

    const html = `
      <div>
        <p>Hello,</p>
        <p>There is a new concierge inquiry. Below is the conversation so far:</p>
        <hr/>
        ${convHtml}
        <hr/>
        <p><strong>Summary:</strong> ${aiSummary || 'No summary available.'}</p>
        <p><strong>Client:</strong> ${parent?.name || '—'} • ${parent?.email || '—'} • ${parent?.phone || '—'}</p>
        <p>This message was auto-generated by the concierge assistant. We’ll review the inquiry and follow up as soon as possible.</p>
        <p><em>Open the admin console to reply or manage this conversation.</em></p>
      </div>
    `;

    // Send via Resend API
    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) return respond(500, { error: 'RESEND_API_KEY not configured' });

    const payload = {
      from,
      to: send_to,
      subject,
      html
    };

    const res = await fetch(RESEND_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${resendKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (!res.ok) {
      const txt = await res.text().catch(() => '');
      console.error('Resend send failed', res.status, txt);
      return respond(502, { error: 'Resend API error', details: txt });
    }

    const sendResp = await res.json();

    return respond(200, { success: true, sent: sendResp });
  } catch (err) {
    console.error('email-summary error', err);
    return respond(500, { error: err.message || String(err) });
  }
};
