// ==========================================================
// FILE: get-about.js
// Get About Page Content from Supabase
// Location: netlify/functions/get-about.js
// ==========================================================
const { supabase, respond } = require("./utils");

exports.handler = async (event) => {
  if (event.httpMethod === "OPTIONS") return respond(200, {});

  if (event.httpMethod !== "GET") {
    return respond(405, { error: "Method not allowed" });
  }

  try {
    // Get the single about page content row
    const { data, error } = await supabase
      .from("about_page")
      .select("*")
      .single();

    if (error && error.code !== 'PGRST116') {
      console.error("Supabase error:", error);
      return respond(500, { error: error.message });
    }

    // If no content exists yet, return defaults
    if (!data) {
      return respond(200, {
        content: {
          hero_title: "Travel, Reimagined.",
          hero_subtitle: "FHJ Dream Destinations was founded on a simple belief: every journey should feel like it was designed just for you — because it was.",
          philosophy_title: "The FHJ Philosophy",
          philosophy_text_1: "We don't sell vacations. We design experiences. Every itinerary is a collaboration — your vision shaped by our expertise, local connections, and obsessive attention to the details that transform a trip into a story you'll tell for years.",
          philosophy_text_2: "From the moment you reach out, you're working with a dedicated travel designer who listens first and plans second. No templates. No generic packages. Just intention, craft, and care.",
          pillar_1_title: "Personal, Not Automated",
          pillar_1_text: "Every trip is designed by a real person who knows your preferences, not generated by an algorithm.",
          pillar_2_title: "Curated Access",
          pillar_2_text: "Private villas, exclusive experiences, local guides — we open doors that aren't on any booking site.",
          pillar_3_title: "24/7 Concierge",
          pillar_3_text: "From the moment you land to the moment you're home, our team is one message away.",
          founder_name: "Farhan Jiwani",
          founder_phone: "",
          founder_email: "",
          founder_bio: "With a passion for world travel and a background in hospitality, Farhan created FHJ Dream Destinations to bridge the gap between luxury and personal touch. What started as planning trips for friends and family grew into a full-service travel design studio trusted by clients across the country.",
          founder_quote: "I believe travel should feel effortless. You dream it — we handle everything else.",
          cta_title: "Ready to Start?",
          cta_subtitle: "Tell us where you want to go. We'll take it from there.",
        }
      });
    }

    return respond(200, { content: data });
  } catch (err) {
    console.error("Get about error:", err);
    return respond(500, { error: err.message });
  }
};
