// ==========================================================
// 📄 FILE: About.jsx  (UPDATED)
// ⭐ Better readability — darker sections over background
// Location: src/pages/About.jsx
// ==========================================================

import React from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { FHJButton, fhjTheme } from "../components/FHJ/FHJUIKit.jsx";
import FHJBackground from "../components/FHJ/FHJBackground.jsx";

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 24 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.7, delay, ease: [0.22, 0.61, 0.36, 1] },
});

export default function About() {
  const navigate = useNavigate();

  return (
    <FHJBackground page="home">
      {/* ⭐ Full-page dark overlay for readability */}
      <div style={overlay}>

        {/* ===== HERO ===== */}
        <section style={heroSection}>
          <motion.p {...fadeUp(0)} style={eyebrow}>
            OUR STORY
          </motion.p>
          <motion.h1 {...fadeUp(0.1)} style={heroTitle}>
            Travel, Reimagined.
          </motion.h1>
          <motion.div {...fadeUp(0.25)} style={divider} />
          <motion.p {...fadeUp(0.3)} style={heroSub}>
            FHJ Dream Destinations was founded on a simple belief: every journey
            should feel like it was designed just for you — because it was.
          </motion.p>
        </section>

        {/* ===== PHILOSOPHY ===== */}
        <section style={sectionStyle}>
          <div style={contentBlock}>
            <motion.h2 {...fadeUp()} style={sectionTitle}>
              The FHJ Philosophy
            </motion.h2>
            <motion.p {...fadeUp(0.1)} style={bodyText}>
              We don't sell vacations. We design experiences. Every itinerary is
              a collaboration — your vision shaped by our expertise, local
              connections, and obsessive attention to the details that
              transform a trip into a story you'll tell for years.
            </motion.p>
            <motion.p {...fadeUp(0.15)} style={bodyText}>
              From the moment you reach out, you're working with a dedicated
              travel designer who listens first and plans second. No templates.
              No generic packages. Just intention, craft, and care.
            </motion.p>
          </div>
        </section>

        {/* ===== PILLARS ===== */}
        <section style={{ ...sectionStyle, paddingBottom: "2rem" }}>
          <motion.h2 {...fadeUp()} style={{ ...sectionTitle, textAlign: "center", marginBottom: "3rem" }}>
            What Sets Us Apart
          </motion.h2>

          <div style={pillarsGrid}>
            {[
              {
                icon: "✦",
                title: "Personal, Not Automated",
                text: "Every trip is designed by a real person who knows your preferences, not generated by an algorithm.",
              },
              {
                icon: "◈",
                title: "Curated Access",
                text: "Private villas, exclusive experiences, local guides — we open doors that aren't on any booking site.",
              },
              {
                icon: "❖",
                title: "24/7 Concierge",
                text: "From the moment you land to the moment you're home, our team is one message away.",
              },
            ].map((pillar, i) => (
              <motion.div
                key={pillar.title}
                {...fadeUp(i * 0.12)}
                style={pillarCard}
              >
                <span style={pillarIcon}>{pillar.icon}</span>
                <h3 style={pillarTitle}>{pillar.title}</h3>
                <p style={pillarText}>{pillar.text}</p>
              </motion.div>
            ))}
          </div>
        </section>

        {/* ===== FOUNDER ===== */}
        <section style={sectionStyle}>
          <motion.div {...fadeUp()} style={founderBlock}>
            <p style={eyebrow}>FOUNDER</p>
            <h2 style={{ ...sectionTitle, marginBottom: "1.25rem" }}>
              Farhan Jiwani
            </h2>
            <p style={bodyText}>
              With a passion for world travel and a background in hospitality,
              Farhan created FHJ Dream Destinations to bridge the gap between
              luxury and personal touch. What started as planning trips for
              friends and family grew into a full-service travel design studio
              trusted by clients across the country.
            </p>
            <p style={{ ...bodyText, color: fhjTheme.primary, fontStyle: "italic", marginTop: "1.5rem", fontSize: "1.1rem" }}>
              "I believe travel should feel effortless. You dream it — we
              handle everything else."
            </p>
          </motion.div>
        </section>

        {/* ===== CTA ===== */}
        <section style={ctaSection}>
          <motion.div {...fadeUp()} style={{ textAlign: "center" }}>
            <h2 style={{ color: "white", fontSize: "2rem", fontWeight: 400, margin: "0 0 1rem", letterSpacing: "0.5px" }}>
              Ready to Start?
            </h2>
            <p style={{ color: "rgba(255,255,255,0.6)", fontSize: "1.05rem", marginBottom: "2.5rem", maxWidth: "480px", marginLeft: "auto", marginRight: "auto" }}>
              Tell us where you want to go. We'll take it from there.
            </p>
            <FHJButton
              onClick={() => navigate("/book")}
              style={{
                padding: "1rem 3rem",
                fontSize: "1rem",
                borderRadius: "50px",
                background: fhjTheme.primary,
                border: "none",
                boxShadow: `0 0 24px rgba(0,196,140,0.3)`,
                letterSpacing: "1px",
              }}
            >
              Plan My Trip
            </FHJButton>
          </motion.div>
        </section>

      </div>
    </FHJBackground>
  );
}

// -------------------------------------------------------
// Styles
// -------------------------------------------------------

// ⭐ Dark overlay so text is always readable over the background
const overlay = {
  position: "relative",
  zIndex: 2,
  background: "linear-gradient(to bottom, rgba(0,0,0,0.45) 0%, rgba(0,0,0,0.7) 30%, rgba(0,0,0,0.8) 60%, rgba(0,0,0,0.9) 100%)",
};

const heroSection = {
  minHeight: "80vh",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  textAlign: "center",
  padding: "10rem 2rem 5rem",
};

const eyebrow = {
  color: fhjTheme.primary,
  fontSize: "0.75rem",
  fontWeight: 600,
  letterSpacing: "4px",
  textTransform: "uppercase",
  marginBottom: "1.25rem",
};

const heroTitle = {
  color: "white",
  fontSize: "clamp(2.5rem, 5.5vw, 3.8rem)",
  fontWeight: 300,
  letterSpacing: "-0.5px",
  margin: 0,
  lineHeight: 1.15,
};

const divider = {
  width: "60px",
  height: "1px",
  background: `linear-gradient(90deg, transparent, ${fhjTheme.primary}, transparent)`,
  margin: "2.5rem auto",
};

const heroSub = {
  color: "rgba(255,255,255,0.75)",
  fontSize: "1.1rem",
  lineHeight: 1.8,
  maxWidth: "560px",
  margin: "0 auto",
};

const sectionStyle = {
  padding: "4rem 2rem",
  maxWidth: "900px",
  margin: "0 auto",
};

const contentBlock = {
  maxWidth: "700px",
};

const sectionTitle = {
  color: "white",
  fontSize: "1.7rem",
  fontWeight: 400,
  letterSpacing: "0.5px",
  margin: "0 0 1.5rem",
};

const bodyText = {
  color: "rgba(255,255,255,0.65)",
  fontSize: "1.02rem",
  lineHeight: 1.9,
  margin: "0 0 1rem",
};

const pillarsGrid = {
  display: "grid",
  gridTemplateColumns: "repeat(3, 1fr)",
  gap: "1.5rem",
  maxWidth: "1000px",
  margin: "0 auto",
};

const pillarCard = {
  padding: "2.25rem 1.5rem",
  background: "rgba(255,255,255,0.03)",
  border: "1px solid rgba(255,255,255,0.08)",
  borderRadius: "18px",
  textAlign: "center",
};

const pillarIcon = {
  display: "block",
  fontSize: "1.4rem",
  color: fhjTheme.primary,
  marginBottom: "1.25rem",
};

const pillarTitle = {
  color: "white",
  fontSize: "1rem",
  fontWeight: 600,
  margin: "0 0 0.75rem",
  letterSpacing: "0.3px",
};

const pillarText = {
  color: "rgba(255,255,255,0.5)",
  fontSize: "0.92rem",
  lineHeight: 1.7,
  margin: 0,
};

const founderBlock = {
  padding: "3rem",
  background: "rgba(255,255,255,0.025)",
  border: "1px solid rgba(255,255,255,0.06)",
  borderRadius: "22px",
};

const ctaSection = {
  padding: "5rem 2rem 8rem",
  maxWidth: "900px",
  margin: "0 auto",
};

// Responsive pillars
if (typeof document !== "undefined") {
  const id = "fhj-about-responsive";
  if (!document.getElementById(id)) {
    const style = document.createElement("style");
    style.id = id;
    style.textContent = `
      @media (max-width: 768px) {
        div[style*="repeat(3, 1fr)"] {
          grid-template-columns: 1fr !important;
        }
      }
    `;
    document.head.appendChild(style);
  }
}
